version: '3'

services:
  db:
    image: mysql/mysql-server:5.7
    container_name: 'db'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_USER: jesse
      MYSQL_PASSWORD: pwd123456
    #volumes:
     # - /d/docker/beta/mysql-init:/docker-entrypoint-initdb.d

      #结束行 enter bug  windows环境有权限问题

  web:
    build: .
    container_name: 'aspnetcore'
    ports:
      - '8003:80'
    depends_on:
      - db